name: Quallity Assurance

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Checking if our app still working
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: sei nao
        run: yarn config list

      - name: Run Linter
        run: yarn lint .

      - name: Run Tests
        run: yarn test
